### ISSUE TITLE
Questions: Will this software work for me ?

### ISSUE THREAD

**Issue by jeevadotnet** [OpenPrinting/ghostscript-printer-app#13]
Good day

**Scenario:**
Family business migrated to a new ERP system over the last 12 months. It is now 3 weeks before 1st March 2024 "Go Live", and the ERP Vendor/ consultants only tell us now that Dot Matrix printers are not supported by their ERP software. We run +- 8 dot matrix printers for the warehouse, and bought 3 new ones just 2 months ago. The are not cheap. We also bought boxes full of per-printed (Stationary) banner paper.

The Epson FX890II /N, Dot matrix printers are USB based and connected to Windows 10 LTSC / Windows 11 machines. New ones are also network-capable. 

**Outcome:**
Will this software allow me to print to a 'fake' printer (or file). And then allow it to be converted to a banner style paper for a dot matrix?

**Flow**
ERP Software >> Windows/linux based computer running VirtualPrinter/File(Ghost)  >> Convert >> Dot Matrix

**Comment by tillkamppeter** [comment]
This app, primarily designed to run under Linux, but also working under Windows using WSL, emulates a driverless IPP printer (so the same as the modern printers you are currently getting in the stores) in software, and this emulated printer can get shared to your local network. So if your ERP supports modern printers, this Printer Application should do the trick.

And as you can create any amount of print queues inside it, you only need to run one instance of it per print server, so if all your dot matrix printers are connected to the same server, one single instance is enough.
