### ISSUE TITLE
Can we increas the stop time out.

### ISSUE THREAD

**Issue by ppywlkiqletw** [OpenPrinting/ghostscript-printer-app#4]
snap is creating this line in the systemd service file
   TimeoutStopSec=30

As pappl  applications in some case have a shutdown delay of 60 seconds, systemd will kill the applicates with SIGKILL preventing it from doing a proper shutdown.  The status files can then be left in an inconsistent state or temporary files not deleted.

In snapcraft.yaml it is possible to set a stop timeout or even a stop command.

```
apps.
<app-name>.
stop-command
        The path to a command inside the snap to run to stop the service.
Type: string
        Requires daemon to be set in app metadata.



apps.
<app-name>.
stop-timeout
        The length of time to wait before terminating a service.
Type: string
        Time duration units can be 10ns, 10us, 10ms, 10s, 10m. Termination
        is via SIGTERM (and SIGKILL if that doesn’t work).
        Requires daemon to be set in the app metadata.

```
If it works, I don't know, it if it works it should be set to somewhat longer that 60 seconds, or perhaps 90 seconds which is the default timeout systemd is using if nothing else is specified.

**Comment by tillkamppeter** [comment]
Fixed in commit 9e9beb90fb2d

Thanks for the bug report.
